"""
Main Automation Pipeline using Playwright (Sync API).
Integrates Proxy Bridge extension, SMS-Activate API, and Mail Service.
"""

import json
import logging
import os
import random
import string
import time
from datetime import datetime
from typing import Dict, Any, Optional

from playwright.sync_api import sync_playwright, BrowserContext, Page

from sms_service import SMSActivateClient, SMSActivateError, SMSActivateTimeoutError
from mail_service import MailClient, MailServiceError, MailTimeoutError

# Configure structured logger
logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger("AutomationPipeline")


def load_config(config_path: str = "config.json") -> Dict[str, Any]:
    """Loads configuration from JSON file."""
    if not os.path.exists(config_path):
        raise FileNotFoundError(f"Configuration file not found: {config_path}")
    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)


def random_sleep(min_sec: float = 1.0, max_sec: float = 2.5):
    """Introduces randomized human-like delay between UI actions."""
    duration = random.uniform(min_sec, max_sec)
    time.sleep(duration)


def human_type(page: Page, selector: str, text: str, delay_min_ms: int = 40, delay_max_ms: int = 120):
    """
    Types text into an input field with randomized keystroke intervals
    to simulate natural human typing.
    """
    page.wait_for_selector(selector, state="visible", timeout=10000)
    page.click(selector)
    for char in text:
        page.keyboard.type(char)
        time.sleep(random.uniform(delay_min_ms, delay_max_ms) / 1000.0)


def generate_random_password(length: int = 14) -> str:
    """Generates a secure alphanumeric password with special symbols."""
    chars = string.ascii_letters + string.digits + "!@#$%^&*"
    return "".join(random.choice(chars) for _ in range(length))


def log_account(
    file_path: str,
    email_addr: str,
    password: str,
    phone: Optional[str] = None,
    notes: Optional[str] = None
):
    """Appends successful account registration details to a local log file."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    entry = (
        f"[{timestamp}] EMAIL: {email_addr} | PASSWORD: {password} | "
        f"PHONE: {phone or 'N/A'} | NOTES: {notes or 'Success'}\n"
    )
    with open(file_path, "a", encoding="utf-8") as f:
        f.write(entry)
    logger.info(f"Account recorded to {file_path}")


class AutomationPipeline:
    """Orchestrates browser automation, proxy injection, and 2FA verification."""

    def __init__(self, config_path: str = "config.json"):
        self.config_path = config_path
        self.config = load_config(config_path)

        # Initialize 3rd-party clients
        self.sms_client = SMSActivateClient(config_path=config_path)
        self.mail_client = MailClient(config_path=config_path)

        # Extension and data paths
        self.base_dir = os.path.dirname(os.path.abspath(__file__))
        self.extension_dir = os.path.join(self.base_dir, "proxy_bridge_ext")
        self.user_data_dir = os.path.join(self.base_dir, "browser_profile")
        self.accounts_file = os.path.join(self.base_dir, "accounts.txt")

    def _sync_extension_config(self):
        """
        Synchronizes proxy parameters from config.json into proxy_bridge_ext/config.js
        before launching the browser.
        """
        proxy_cfg = self.config.get("proxy", {})
        config_js_path = os.path.join(self.extension_dir, "config.js")

        js_content = f"""/**
 * Auto-generated by AutomationPipeline from config.json
 */
export const DEFAULT_PROXY_CONFIG = {{
  enabled: {str(proxy_cfg.get("enabled", True)).lower()},
  scheme: "{proxy_cfg.get("scheme", "http")}",
  host: "{proxy_cfg.get("host", "127.0.0.1")}",
  port: {proxy_cfg.get("port", 8080)},
  username: "{proxy_cfg.get("username", "")}",
  password: "{proxy_cfg.get("password", "")}",
  bypassList: {json.dumps(proxy_cfg.get("bypass_list", ["localhost", "127.0.0.1"]))}
}};
"""
        with open(config_js_path, "w", encoding="utf-8") as f:
            f.write(js_content)
        logger.info(f"Synchronized proxy settings to {config_js_path}")

    def find_chrome_path(self) -> Optional[str]:
        """Finds Google Chrome or Edge executable on the system."""
        candidates = [
            r"C:\Program Files\Google\Chrome\Application\chrome.exe",
            r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
            os.path.expandvars(r"%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe"),
            r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
        ]
        for path in candidates:
            if os.path.exists(path):
                return path
        return None

    def launch_browser(self, playwright_instance) -> BrowserContext:
        """
        Launches real Chrome/Chromium persistent context with stealth anti-detection
        and optional Proxy Bridge extension.
        """
        proxy_enabled = self.config.get("proxy", {}).get("enabled", False)

        args = [
            "--disable-blink-features=AutomationControlled",
            "--no-first-run",
            "--no-default-browser-check",
            "--disable-infobars",
            "--start-maximized",
        ]

        if proxy_enabled:
            self._sync_extension_config()
            args.extend([
                f"--disable-extensions-except={self.extension_dir}",
                f"--load-extension={self.extension_dir}",
            ])

        chrome_exe = self.find_chrome_path()
        if chrome_exe:
            logger.info(f"Using Real Chrome executable: {chrome_exe}")
        else:
            logger.warning("Real Chrome not found, falling back to bundled Chromium.")

        logger.info(f"Launching browser context with profile at {self.user_data_dir}...")
        context = playwright_instance.chromium.launch_persistent_context(
            user_data_dir=self.user_data_dir,
            executable_path=chrome_exe,
            headless=False,
            args=args,
            no_viewport=True,
            locale="en-US",
            timezone_id="America/New_York",
            slow_mo=50
        )

        # Inject Stealth scripts to bypass bot detection (Cloudflare / Turnstile)
        context.add_init_script("""
            Object.defineProperty(navigator, 'webdriver', {
                get: () => undefined
            });
            window.chrome = {
                app: { isInstalled: false, InstallState: { DISABLED: 'disabled' }, RunningState: { CANNOT_RUN: 'cannot_run' } },
                runtime: { OnInstalledReason: { INSTALL: 'install' }, PlatformOs: { WIN: 'win' } },
            };
            Object.defineProperty(navigator, 'languages', {
                get: () => ['en-US', 'en', 'vi']
            });
            Object.defineProperty(navigator, 'plugins', {
                get: () => [1, 2, 3, 4, 5]
            });
        """)

        return context

    def verify_proxy_ip(self, page: Page):
        """Optional health check: Navigates to an IP check service to verify proxy routing."""
        logger.info("Verifying proxy IP address...")
        try:
            page.goto("https://httpbin.org/ip", timeout=20000)
            logger.info(f"Proxy Response: {page.inner_text('body')}")
        except Exception as e:
            logger.warning(f"Could not verify IP via httpbin: {e}")

    def run_signup_pipeline(self, target_email: str, target_password: Optional[str] = None):
        """
        Executes the end-to-end registration flow skeleton.
        """
        password = target_password or generate_random_password()
        activation_id = None
        phone_number = None

        with sync_playwright() as p:
            context = self.launch_browser(p)
            page = context.pages[0] if context.pages else context.new_page()

            try:
                # -------------------------------------------------------------
                # Step 1: Proxy Verification
                # -------------------------------------------------------------
                if self.config.get("proxy", {}).get("enabled", False):
                    self.verify_proxy_ip(page)
                    random_sleep(1.5, 3.0)

                # -------------------------------------------------------------
                # Step 2: Open Target Registration Page
                # -------------------------------------------------------------
                target_url = "https://example.com/signup"  # Replace with target registration URL
                logger.info(f"Navigating to signup page: {target_url}")
                page.goto(target_url, wait_until="domcontentloaded", timeout=30000)
                random_sleep(2.0, 4.0)

                # -------------------------------------------------------------
                # Step 3: Fill Credentials Form
                # (Adapt selectors to match the target form)
                # -------------------------------------------------------------
                logger.info(f"Entering email: {target_email}")
                # Example: human_type(page, "input[name='email']", target_email)
                random_sleep(1.0, 2.0)

                logger.info("Entering password...")
                # Example: human_type(page, "input[name='password']", password)
                random_sleep(1.0, 2.0)

                logger.info("Submitting registration form...")
                # Example: page.click("button[type='submit']")
                random_sleep(3.0, 5.0)

                # -------------------------------------------------------------
                # Step 4: Email Verification (OTP or Activation Link)
                # -------------------------------------------------------------
                logger.info("Awaiting email verification...")
                try:
                    # Fetch OTP code from mailbox
                    mail_otp = self.mail_client.wait_for_otp(
                        filter_subject="Verification",
                        timeout=120,
                        poll_interval=5
                    )
                    logger.info(f"Received Mail OTP: {mail_otp}")
                    # Example: human_type(page, "input[name='email_otp']", mail_otp)
                    random_sleep(1.5, 3.0)
                except (MailServiceError, MailTimeoutError) as mail_err:
                    logger.warning(f"Mail verification step skipped or failed: {mail_err}")

                # -------------------------------------------------------------
                # Step 5: SMS Phone Verification
                # -------------------------------------------------------------
                sms_cfg = self.config.get("sms_activate", {})
                service_name = sms_cfg.get("default_service", "openai")
                country_id = sms_cfg.get("default_country", "0")

                logger.info(f"Ordering virtual number (service={service_name}, country={country_id})...")
                try:
                    activation_id, phone_number = self.sms_client.get_number(
                        service=service_name,
                        country=country_id
                    )
                    logger.info(f"Entering phone number: +{phone_number}")
                    # Example: human_type(page, "input[name='phone_number']", phone_number)
                    # Example: page.click("button#send_sms")

                    # Wait for incoming SMS code
                    sms_code = self.sms_client.get_sms_code(activation_id, timeout=120)
                    logger.info(f"Received SMS OTP: {sms_code}")
                    # Example: human_type(page, "input[name='sms_otp']", sms_code)
                    # Example: page.click("button#confirm_sms")
                    random_sleep(2.0, 4.0)

                except (SMSActivateError, SMSActivateTimeoutError) as sms_err:
                    logger.error(f"SMS verification failed: {sms_err}")
                    if activation_id:
                        self.sms_client.cancel_number(activation_id)
                    raise

                # -------------------------------------------------------------
                # Step 6: Log Account Details
                # -------------------------------------------------------------
                log_account(
                    file_path=self.accounts_file,
                    email_addr=target_email,
                    password=password,
                    phone=phone_number,
                    notes="Registered successfully"
                )
                logger.info("Signup pipeline completed successfully.")

            except Exception as e:
                logger.error(f"Pipeline execution error: {e}", exc_info=True)
                if activation_id:
                    logger.info(f"Cleaning up activation ID {activation_id}...")
                    try:
                        self.sms_client.cancel_number(activation_id)
                    except Exception:
                        pass
            finally:
                logger.info("Closing browser context...")
                context.close()


if __name__ == "__main__":
    from reg_cdp import run_cdp_registration
    run_cdp_registration()
